### ISSUE TITLE
Update Register Page with current detail

### ISSUE THREAD

**Issue by pcrowecookies** [kellychurchill/boothapp#1]
If you think I can do it, send me the details and I will take care of it.

**Comment by kellychurchill** [comment]
I updated the year display so that it will always display the current year automatically.  This will prevent us from having to make the same update annually. 

http://ohsucookies.com/auth/register

@pcrowecookies were there any other updates needed other than the new fields outlined in #2?

**Comment by kellychurchill** [comment]
@pcrowecookies is the year the only update other than the new fields from #2?

**Comment by pcrowecookies** [comment]
yes..that is it.  Thank you!
